/// Blade's built-in directives: label and snippet, from Laravel LSP's list.
pub const DIRECTIVES: &[(&str, &str)] = &[
    ("@if(...)", "@if (${1})\n\t${2}\n@endif"),
    ("@error(...)", "@error(${1})\n\t${2}\n@enderror"),
    ("@if(...) ... @else ... @endif", "@if (${1})\n\t${2}\n@else\n\t${3}\n@endif"),
    ("@foreach(...)", "@foreach (${1} as ${2})\n\t${3}\n@endforeach"),
    ("@forelse(...)", "@forelse (${1} as ${2})\n\t${3}\n@empty\n\t${4}\n@endforelse"),
    ("@for(...)", "@for (${1})\n\t${2}\n@endfor"),
    ("@while(...)", "@while (${1})\n\t${2}\n@endwhile"),
    ("@switch(...)", "@switch(${1})\n\t@case(${2})\n\t\t${3}\n\t\t@break\n\n\t@default\n\t\t${4}\n@endswitch"),
    ("@case(...)", "@case(${1})\n\t${2}\n@break"),
    ("@break", "@break"),
    ("@continue", "@continue"),
    ("@break(...)", "@break(${1})"),
    ("@continue(...)", "@continue(${1})"),
    ("@default", "@default"),
    ("@extends(...)", "@extends(${1})"),
    ("@empty", "@empty"),
    ("@verbatim ...", "@verbatim\n\t${1}\n@endverbatim"),
    ("@json(...)", "@json(${1})"),
    ("@elseif (...)", "@elseif (${1})"),
    ("@else", "@else"),
    ("@unless(...)", "@unless (${1})\n\t${2}\n@endunless"),
    ("@isset(...)", "@isset(${1})\n\t${2}\n@endisset"),
    ("@empty(...)", "@empty(${1})\n\t${2}\n@endempty"),
    ("@auth", "@auth\n\t${1}\n@endauth"),
    ("@guest", "@guest\n\t${1}\n@endguest"),
    ("@auth(...)", "@auth(${1})\n\t${2}\n@endauth"),
    ("@guest(...)", "@guest(${1})\n\t${2}\n@endguest"),
    ("@can(...)", "@can(${1})\n\t${2}\n@endcan"),
    ("@cannot(...)", "@cannot(${1})\n\t${2}\n@endcannot"),
    ("@elsecan(...)", "@elsecan(${1})"),
    ("@elsecannot(...)", "@elsecannot(${1})"),
    ("@production", "@production\n\t${1}\n@endproduction"),
    ("@env(...)", "@env(${1})\n\t${2}\n@endenv"),
    ("@hasSection(...)", "@hasSection(${1})\n\t${2}\n@endif"),
    ("@sectionMissing(...)", "@sectionMissing(${1})\n${2}\n@endif"),
    ("@include(...)", "@include(${1})"),
    ("@includeIf(...)", "@includeIf(${1})"),
    ("@includeWhen(...)", "@includeWhen(${1}, ${2})"),
    ("@includeUnless(...)", "@includeUnless(${1}, ${2})"),
    ("@includeFirst(...)", "@includeFirst(${1})"),
    ("@each(...)", "@each(${1}, ${2}, ${3})"),
    ("@once", "@once\n\t${1}\n@endonce"),
    ("@yield(...)", "@yield(${1})"),
    ("@slot(...)", "@slot(${1})"),
    ("@stack(...)", "@stack(${1})"),
    ("@push(...)", "@push(${1})\n\t${2}\n@endpush"),
    ("@pushIf(...)", "@pushIf(${1})\n\t${2}\n@endPushIf"),
    ("@pushOnce(...)", "@pushOnce(${1})\n\t${2}\n@endPushOnce"),
    ("@prepend(...)", "@prepend(${1})\n\t${2}\n@endprepend"),
    ("@php", "@php\n\t${1}\n@endphp"),
    ("@component(...)", "@component(${1})\n${2}\n@endcomponent"),
    ("@section(...) ... @endsection", "@section(${1})\n${2}\n@endsection"),
    ("@section(...)", "@section(${1})"),
    ("@props(...)", "@props(${1})"),
    ("@use(...)", "@use(${1})"),
    ("@show", "@show"),
    ("@stop", "@stop"),
    ("@parent", "@parent"),
    ("@csrf", "@csrf"),
    ("@method(...)", "@method(${1})"),
    ("@inject(...)", "@inject(${1}, ${2})"),
    ("@dump(...)", "@dump(${1})"),
    ("@dd(...)", "@dd(${1})"),
    ("@lang(...)", "@lang(${1})"),
    ("@endif", "@endif"),
    ("@enderror", "@enderror"),
    ("@endforeach", "@endforeach"),
    ("@endforelse", "@endforelse"),
    ("@endfor", "@endfor"),
    ("@endwhile", "@endwhile"),
    ("@endswitch", "@endswitch"),
    ("@endverbatim", "@endverbatim"),
    ("@endunless", "@endunless"),
    ("@endisset", "@endisset"),
    ("@endempty", "@endempty"),
    ("@endauth", "@endauth"),
    ("@endguest", "@endguest"),
    ("@endproduction", "@endproduction"),
    ("@endenv", "@endenv"),
    ("@endonce", "@endonce"),
    ("@endpush", "@endpush"),
    ("@endpushIf", "@endPushIf"),
    ("@endpushOnce", "@endPushOnce"),
    ("@endprepend", "@endprepend"),
    ("@endphp", "@endphp"),
    ("@endcomponent", "@endcomponent"),
    ("@endsection", "@endsection"),
    ("@endslot", "@endslot"),
    ("@endcan", "@endcan"),
    ("@endcannot", "@endcannot"),
];

/// Validation rules: label and snippet.
pub const RULES: &[(&str, &str)] = &[
    ("accepted", "accepted"),
    ("active_url", "active_url"),
    ("after_or_equal", "after_or_equal:${1:date}"),
    ("after", "after:${1:date}"),
    ("alpha_dash", "alpha_dash"),
    ("alpha_num", "alpha_num"),
    ("alpha", "alpha"),
    ("array", "array"),
    ("ascii", "ascii"),
    ("bail", "bail"),
    ("before_or_equal", "before_or_equal:${1:date}"),
    ("before", "before:${1:date}"),
    ("between", "between:${1:min},${2:max}"),
    ("boolean", "boolean"),
    ("confirmed", "confirmed"),
    ("current_password", "current_password:${1:api}"),
    ("date_equals", "date_equals:${1:date}"),
    ("date_format", "date_format:${1:format}"),
    ("date", "date"),
    ("decimal", "decimal:${1:min},${2:max}"),
    ("declined_if", "declined_if:${1:anotherfield},${2:value}"),
    ("declined", "declined"),
    ("different", "different:${1:field}"),
    ("digits_between", "digits_between:${1:min},${2:max}"),
    ("digits", "digits:${1:value}"),
    ("dimensions", "dimensions"),
    ("distinct", "distinct"),
    ("doesnt_end_with", "doesnt_end_with:${1:foo},${2:bar}"),
    ("doesnt_start_with", "doesnt_start_with:${1:foo},${2:bar}"),
    ("email", "email"),
    ("ends_with", "ends_with:${1}"),
    ("exists", "exists:${2:table},${3:column}"),
    ("file", "file"),
    ("filled", "filled"),
    ("gt", "gt:${1:field}"),
    ("gte", "gte:${1:field}"),
    ("image", "image"),
    ("in_array", "in_array:${1:anotherfield.*}"),
    ("in", "in:${1:something},${2:something else}"),
    ("integer", "integer"),
    ("ip", "ip"),
    ("ipv4", "ipv4"),
    ("ipv6", "ipv6"),
    ("json", "json"),
    ("lowercase", "lowercase"),
    ("lt", "lt:${1:field}"),
    ("lte", "lte:${1:field}"),
    ("mac_address", "mac_address"),
    ("max_digits", "max_digits:${1:value}"),
    ("max", "max:${1:value}"),
    ("mimes", "mimes:${1:png,jpg}"),
    ("mimetypes", "mimetypes:${1:text/plain}"),
    ("min_digits", "min_digits:${1:value}"),
    ("min", "min:${1:value}"),
    ("multiple_of", "multiple_of:${1:value}"),
    ("not_in", "not_in:${1:something},${2:something else}"),
    ("not_regex", "not_regex:${1:pattern}"),
    ("nullable", "nullable"),
    ("numeric", "numeric"),
    ("password", "password"),
    ("present", "present"),
    ("prohibited_if", "prohibited_if:${1:anotherfield},${2:value}"),
    ("prohibited_unless", "prohibited_unless:${1:anotherfield},${2:value}"),
    ("prohibited", "prohibited"),
    ("regex", "regex:${1:pattern}"),
    ("required_array_keys", "required_array_keys:${1:foo},${2:bar}"),
    ("required_if", "required_if:${1:anotherfield},${2:value}"),
    ("required_unless", "required_unless:${1:anotherfield},${2:value}"),
    ("required_with_all", "required_with_all:${1:anotherfield},${2:anotherfield}"),
    ("required_with", "required_with:${1:anotherfield}"),
    ("required_without_all", "required_without_all:${1:anotherfield},${2:anotherfield}"),
    ("required_without", "required_without:${1:anotherfield}"),
    ("required", "required"),
    ("same", "same:${1:field}"),
    ("size", "size:${1:value}"),
    ("sometimes", "sometimes"),
    ("starts_with", "starts_with:${1:foo},${2:bar}"),
    ("string", "string"),
    ("timezone", "timezone"),
    ("unique", "unique:${1:table},${2:column},${3:except},${4:id}"),
    ("uppercase", "uppercase"),
    ("url", "url"),
    ("uuid", "uuid"),
];
