// Monaco themes that match the UI colors, with syntax colors close to PhpStorm's
// "Dark" and "Light" schemes.
import { monaco } from "./editor";

type Rule = monaco.editor.ITokenThemeRule;

/** Token colors, by the token names Monaco's PHP, HTML, Blade, JavaScript, and CSS grammars emit. */
function rules(c: Record<string, string>): Rule[] {
  const r = (token: string, foreground: string, fontStyle?: string): Rule => ({ token, foreground: foreground.slice(1), fontStyle });
  return [
    r("", c.text),
    r("comment", c.comment, "italic"),
    r("comment.doc", c.docComment, "italic"),
    r("keyword", c.keyword),
    r("keyword.flow", c.keyword),
    r("storage", c.keyword),
    r("string", c.string),
    r("string.escape", c.keyword),
    r("number", c.number),
    r("regexp", c.string),
    r("variable", c.variable),
    r("variable.predefined", c.keyword),
    r("identifier", c.text),
    r("type", c.type),
    r("type.identifier", c.type),
    r("delimiter", c.text),
    r("operator", c.text),
    r("metatag", c.keyword),
    r("metatag.php", c.keyword),
    r("tag", c.tag),
    r("attribute.name", c.attribute),
    r("attribute.value", c.string),
    r("keyword.blade", c.keyword),
    r("delimiter.blade", c.keyword),
    r("comment.blade", c.comment, "italic"),
    r("key", c.field),
    r("string.key.json", c.field),
    r("string.value.json", c.string),
    r("attribute.name.css", c.field),
    r("attribute.value.css", c.string),
    r("attribute.value.number.css", c.number),
    r("attribute.value.unit.css", c.number),
    r("tag.css", c.tag),
    r("keyword.md", c.keyword),
    r("emphasis", c.text, "italic"),
    r("strong", c.text, "bold"),
  ];
}

export function defineThemes() {
  monaco.editor.defineTheme("editor-dark", {
    base: "vs-dark",
    inherit: true,
    rules: rules({
      text: "#bcbec4", comment: "#7a7e85", docComment: "#5f826b", keyword: "#cf8e6d", string: "#6aab73", number: "#2aacb8",
      variable: "#bcbec4", type: "#bcbec4", tag: "#d5b778", attribute: "#bababa", field: "#c77dbb",
    }),
    colors: {
      "editor.background": "#1e1f22",
      "editor.foreground": "#bcbec4",
      "editor.lineHighlightBackground": "#26282e",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#214283",
      "editor.inactiveSelectionBackground": "#21428366",
      "editor.wordHighlightBackground": "#373b3980",
      "editor.findMatchBackground": "#32593d",
      "editor.findMatchHighlightBackground": "#2f4d3a80",
      "editorLineNumber.foreground": "#4b5059",
      "editorLineNumber.activeForeground": "#a1a3ab",
      "editorIndentGuide.background1": "#2c2e33",
      "editorIndentGuide.activeBackground1": "#43454a",
      "editorWhitespace.foreground": "#34363b",
      "editorGutter.background": "#1e1f22",
      "editorCursor.foreground": "#ced0d6",
      "editorBracketMatch.background": "#43454a",
      "editorBracketMatch.border": "#00000000",
      "editorInlayHint.background": "#2b2d30",
      "editorInlayHint.foreground": "#8c8f94",
      "editorCodeLens.foreground": "#6f737a",
      "editorWidget.background": "#2b2d30",
      "editorWidget.border": "#43454a",
      "editorSuggestWidget.background": "#2b2d30",
      "editorSuggestWidget.border": "#43454a",
      "editorSuggestWidget.selectedBackground": "#2e436e",
      "editorHoverWidget.background": "#2b2d30",
      "editorHoverWidget.border": "#43454a",
      "list.hoverBackground": "#393b40",
      "list.activeSelectionBackground": "#2e436e",
      "scrollbarSlider.background": "#4e515766",
      "scrollbarSlider.hoverBackground": "#5a5d6399",
      "scrollbarSlider.activeBackground": "#6f737a99",
      "editorOverviewRuler.border": "#00000000",
      "peekViewEditor.background": "#1e1f22",
      "peekViewResult.background": "#2b2d30",
      "peekViewTitle.background": "#2b2d30",
      "diffEditor.insertedTextBackground": "#54915933",
      "diffEditor.removedTextBackground": "#e06c7533",
    },
  });
  monaco.editor.defineTheme("editor-light", {
    base: "vs",
    inherit: true,
    rules: rules({
      text: "#080808", comment: "#8c8c8c", docComment: "#8c8c8c", keyword: "#0033b3", string: "#067d17", number: "#1750eb",
      variable: "#080808", type: "#000000", tag: "#0033b3", attribute: "#174ad4", field: "#871094",
    }),
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#080808",
      "editor.lineHighlightBackground": "#f5f8fe",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#a6d2ff",
      "editorLineNumber.foreground": "#aeb3c2",
      "editorLineNumber.activeForeground": "#767a8a",
      "editorIndentGuide.background1": "#ebecf0",
      "editorIndentGuide.activeBackground1": "#c9ccd6",
      "editorGutter.background": "#ffffff",
      "editorInlayHint.background": "#f2f3f5",
      "editorInlayHint.foreground": "#818594",
      "editorCodeLens.foreground": "#818594",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#dfe1e5",
      "editorSuggestWidget.selectedBackground": "#d5e1ff",
      "list.activeSelectionBackground": "#d5e1ff",
      "list.activeSelectionForeground": "#000000",
      "scrollbarSlider.background": "#a0a3ad55",
      "scrollbarSlider.hoverBackground": "#a0a3ad88",
      "editorOverviewRuler.border": "#00000000",
    },
  });
}
